"""Production operation handlers and their domain errors."""

from kkb_agent.agent.handlers.deflate_column import (
    DEFLATION_CONVENTION,
    DeflateBasePeriodMissingError,
    DeflateBasePeriodNotFoundError,
    DeflateCalculationError,
    DeflateColumnCollisionError,
    DeflateColumnError,
    DeflateColumnNotFoundError,
    DeflateColumnTypeError,
    DeflateConventionError,
    DeflateDeflatorMeasureError,
    DeflateDeflatorValueError,
    DeflateSpineTypeError,
    DeflateTargetMeasureError,
    deflate_column_handler,
    deflated_column_key,
)
from kkb_agent.agent.handlers.index_column import (
    IndexBasePeriodMissingError,
    IndexBasePeriodNotFoundError,
    IndexBaseValueZeroError,
    IndexCalculationError,
    IndexColumnCollisionError,
    IndexColumnError,
    IndexColumnNotFoundError,
    IndexColumnTypeError,
    IndexSpineTypeError,
    index_column_handler,
    indexed_column_key,
)

__all__ = [
    "DEFLATION_CONVENTION",
    "DeflateBasePeriodMissingError",
    "DeflateBasePeriodNotFoundError",
    "DeflateCalculationError",
    "DeflateColumnCollisionError",
    "DeflateColumnError",
    "DeflateColumnNotFoundError",
    "DeflateColumnTypeError",
    "DeflateConventionError",
    "DeflateDeflatorMeasureError",
    "DeflateDeflatorValueError",
    "DeflateSpineTypeError",
    "DeflateTargetMeasureError",
    "IndexBasePeriodMissingError",
    "IndexBasePeriodNotFoundError",
    "IndexBaseValueZeroError",
    "IndexCalculationError",
    "IndexColumnCollisionError",
    "IndexColumnError",
    "IndexColumnNotFoundError",
    "IndexColumnTypeError",
    "IndexSpineTypeError",
    "deflate_column_handler",
    "deflated_column_key",
    "index_column_handler",
    "indexed_column_key",
]
