"""URL agent: route fetched content to the handler for its actual media type."""

from kkb_agent.tools.url_agent.handlers import (
    DEFAULT_LIMITS,
    ExtractionLimits,
    content_sha256,
    extract_excel,
    extract_html,
    extract_text,
)
from kkb_agent.tools.url_agent.models import (
    ContentExtractionError,
    DocumentKind,
    ExtractedLink,
    ExtractedPage,
    ExtractedTable,
    OCRBackendError,
    PDFTextLayerMissingError,
    UnimplementedContentTypeError,
    UnsupportedContentTypeError,
    URLAgentError,
    URLDocument,
)
from kkb_agent.tools.url_agent.ocr import (
    MAX_IMAGES_PER_CALL,
    MULTI_IMAGE_WINDOW_SIZE,
    SINGLE_IMAGE_WINDOW_SIZE,
    MIAOCRBackend,
    OCRBackend,
    OCRCache,
    extract_image,
    ocr_images,
    strip_layout_tags,
)
from kkb_agent.tools.url_agent.pdf import extract_pdf
from kkb_agent.tools.url_agent.router import (
    GENERIC_MEDIA_TYPES,
    MEDIA_TYPE_KINDS,
    ContentHandler,
    ContentTypeRouter,
    create_content_type_router,
    sniff_kind,
)

__all__ = [
    "DEFAULT_LIMITS",
    "GENERIC_MEDIA_TYPES",
    "MAX_IMAGES_PER_CALL",
    "MEDIA_TYPE_KINDS",
    "MULTI_IMAGE_WINDOW_SIZE",
    "SINGLE_IMAGE_WINDOW_SIZE",
    "ContentExtractionError",
    "ContentHandler",
    "ContentTypeRouter",
    "DocumentKind",
    "ExtractedLink",
    "ExtractedPage",
    "ExtractedTable",
    "ExtractionLimits",
    "MIAOCRBackend",
    "OCRBackend",
    "OCRBackendError",
    "OCRCache",
    "PDFTextLayerMissingError",
    "URLAgentError",
    "URLDocument",
    "UnimplementedContentTypeError",
    "UnsupportedContentTypeError",
    "content_sha256",
    "create_content_type_router",
    "extract_excel",
    "extract_html",
    "extract_image",
    "extract_pdf",
    "extract_text",
    "ocr_images",
    "sniff_kind",
    "strip_layout_tags",
]
